/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _CostRoute } from '../pages/cost';
import { Route as _IndexRoute } from '../pages/';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/cost': (typeof _CostRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/cost': (typeof _CostRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
  }
}
