/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _FavoritesRoute } from '../pages/favorites';
import { Route as _IndexRoute } from '../pages/';
import { Route as _RecipeRoute } from '../pages/recipe';
import { Route as _ResultRoute } from '../pages/result';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/favorites': (typeof _FavoritesRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/recipe': (typeof _RecipeRoute)['_inputType'];
    '/result': (typeof _ResultRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/favorites': (typeof _FavoritesRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/recipe': (typeof _RecipeRoute)['_outputType'];
    '/result': (typeof _ResultRoute)['_outputType'];
  }
}
